import os
from txtai import Embeddings, LLM
import matplotlib.pyplot as plt
import networkx as nx
from matplotlib import cm
import platform

# Ensure single-threaded operation on arm devices
if platform.processor() == "arm":
    os.environ["OMP_NUM_THREADS"] = "1"

# Create embeddings instance with your configuration
embeddings = Embeddings({
    "autoid": "uuid5",
    "path": "intfloat/e5-base",
    "instructions": {
        "query": "query: ",
        "data": "passage: "
    },
    "content": True,
    "graph": {
        "approximate": False,
        "topics": {}
    }
})

# Load a prebuilt index for RAG embeddings (if available)
rag_embed = Embeddings()
rag_embed.load(os.path.abspath(os.pardir) + "/app/cache/embeddings")

# Build the embeddings index using BM25-style (or your existing) search results
query = """
SELECT id, text FROM txtai
order by percentile desc
LIMIT 100000
"""
embeddings.index(rag_embed.search(query))

# Create the graph from a search query (adjust the query as needed)
graph = embeddings.search("UFSC Blumenau", 50, graph=True)


# Optionally, define a plotting function (same as before)
def plot(graph):
    labels = {x: f"{graph.attribute(x, 'id')[:10]} ({x})" for x in graph.scan()}

    backend = graph.backend
    degrees = dict(backend.degree())
    max_degree = max(degrees.values()) if degrees else 1
    node_colors = [cm.viridis(degrees[node] / max_degree) for node in backend.nodes()]

    pos = nx.spring_layout(backend, seed=42, k=0.9, iterations=100)

    fig, ax = plt.subplots(figsize=(20, 10))

    nx.draw_networkx_nodes(
        backend, pos,
        node_size=800,
        node_color=node_colors,
        alpha=0.9
    )

    nx.draw_networkx_edges(
        backend, pos,
        edge_color="#454545",
        width=1.5,
        alpha=0.8
    )

    nx.draw_networkx_labels(
        backend, pos,
        labels=labels,
        font_size=10,
        font_color="white",
        font_weight="bold",
        bbox=dict(facecolor="#303030", edgecolor="none", boxstyle="round,pad=0.2")
    )

    ax.set_axis_off()
    ax.set_facecolor("#303030")
    fig.set_facecolor("#ffffff")

    plt.title("Base de conhecimento UFSC Blumenau", fontsize=16, color="white", pad=20)
    plt.tight_layout()
    plt.savefig("graph.png", dpi=300)
    plt.show()


plot(graph)

# Initialize your LLM (make sure the MODEL_ID environment variable is set)
llm = LLM(os.getenv("MODEL_ID"))


# This function refines the topics generated by the graph using the node text.
def refine_topics(graph, llm):
    refined_topics = {}
    # Iterate over all topic keys in the graph's topics dictionary
    for original_topic in graph.topics.keys():
        # Combine text from each node belonging to the topic
        combined_text = "\n".join(graph.attribute(uid, "text") for uid in graph.topics[original_topic])

        # Create a prompt to generate a concise topic label
        prompt = f"""<|im_start|>system
You are a friendly assistant. Your task is to generate a concise, descriptive topic label in just a few words.
<|im_end|>
<|im_start|>user
Based on the following texts, please generate a refined topic label:
{combined_text}
Refined topic label: <|im_end|>
<|im_start|>assistant"""

        # Generate the refined topic using the LLM (adjust maxlength if needed)
        refined_label = llm(prompt, maxlength=512).strip()
        refined_topics[original_topic] = refined_label

        print(f"Original Topic Key: {original_topic}")
        print(f"Refined Topic Label: {refined_label}\n")

    return refined_topics


# Generate refined topics using the node texts in the graph
refined = refine_topics(graph, llm)
